language: node_js

node_js:
  - "12"
before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl--pre
  - gem install bundler
  - yarn install
script:
  - yarn build

deploy:
  provider: heroku
  app: test-tsp
  api_key:
    secure: 47b5cd0a-296e-4514-8e63-ce749b0791d7
