language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - "12"
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  on:
    branch: master
